global:
  namespace: "default"

## Pod Labels
labels:
  app: "webl0r" 

## Frontend Config
webDeployment:
  name: frontend
  dockerImage: "zepp/fintest"
  dockerTag: "42"
  replicas: 6
  port: 8000
  updateType: "RollingUpdate"
  readysec: 5
  maxUnavailable: 0
  maxSurge: 3
webService:
  name: web1337
  port: 80
  portProtocol: "TCP"
  port: 80
webIngress:
  path: "/"
  url: "test.example.com"
  anno: "traefik"

## Sidecar
sideDeployment:
  name: sidecar
  dockerImage: "zepp/fintest"
  dockerTag: "31"
  replicas: 3
  port: 8000
  updateType: "RollingUpdate"
  readysec: 5
  maxUnavailable: 0
  maxSurge: 3
sideService:
  name: sidecars
  port: 80
  portProtocol: "TCP"
  port: 80
sideIngress:
  path: "/"
  url: "sidecar.example.com"
  anno: "traefik"

## Backend
backendDeployment:
  name: backend
  dockerImage: "zepp/fintest"
  dockerTag: "30"
  replicas: 3
  port: 8000
  updateType: "RollingUpdate"
  readysec: 5
  maxUnavailable: 0
  maxSurge: 3
backendService:
  name: webend
  port: 80
  portProtocol: "TCP"
  port: 80
backendIngress:
  path: "/"
  url: "backend.example.com"
  anno: "traefik"