global:
  namespace: "default"

## Pod Labels
labels:
  app: "webl0r" 

## Frontend Config
webDeployment:
  name: frontend
  dockerImage: "zepp/fintest"
  dockerTag: "43"
  replicas: 3
  port: 8000
  updateType: "RollingUpdate"
  readysec: 5
  maxUnavailable: 0
  maxSurge: 3
webService:
  name: web-fronti
  port: 80
  portProtocol: "TCP"
  port: 80
webIngress:
  path: "/"
  url: "test.example.com"
  anno: "traefik"

## Sidecar
sideDeployment:
  name: sidecar
  dockerImage: "zepp/fintest"
  dockerTag: "43"
  replicas: 3
  port: 8000
  updateType: "RollingUpdate"
  readysec: 5
  maxUnavailable: 0
  maxSurge: 3
sideService:
  name: web-sidecar
  port: 80
  portProtocol: "TCP"
  port: 80
sideIngress:
  path: "/"
  url: "sidecar.example.com"
  anno: "traefik"

## Backend
backendDeployment:
  name: backend
  dockerImage: "zepp/fintest"
  dockerTag: "43"
  replicas: 3
  port: 8000
  updateType: "RollingUpdate"
  readysec: 5
  maxUnavailable: 0
  maxSurge: 3
backendService:
  name: web-backi
  port: 80
  portProtocol: "TCP"
  port: 80
backendIngress:
  path: "/"
  url: "backend.example.com"
  anno: "traefik"

## Policy - this rule allows no traffic from sidecar to frontend
policy:
  name: allow-helm
  hitlabel: restrictme
  allowlabel: letmein