apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backendDeployment.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.backendDeployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backendDeployment.name }}
  strategy:
    type: {{ .Values.backendDeployment.updateType }}
    rollingUpdate:
      maxSurge: {{ .Values.backendDeployment.maxSurge }}
      maxUnavailable: {{ .Values.backendDeployment.maxUnavailable }}
  minReadySeconds: {{ .Values.backendDeployment.readysec }}
  template:
    metadata:
      labels:
        app: {{ .Values.backendDeployment.name }}
        role: {{ .Values.policy.allowlabel }}
    spec:
      containers:
      - name: {{ .Values.backendDeployment.name }}
        image: {{ .Values.backendDeployment.dockerImage }}:{{ .Values.backendDeployment.dockerTag }}
        ports:
        - containerPort: {{ .Values.backendDeployment.port }}