apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webDeployment.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.webDeployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.webDeployment.name }}
  strategy:
    type: {{ .Values.webDeployment.updateType }}
    rollingUpdate:
      maxSurge: {{ .Values.webDeployment.maxSurge }}
      maxUnavailable: {{ .Values.webDeployment.maxUnavailable }}
  minReadySeconds: {{ .Values.webDeployment.readysec }}
  template:
    metadata:
      labels:
        app: {{ .Values.webDeployment.name }}
        role: {{ .Values.policy.hitlabel }}
    spec:
      containers:
      - name: {{ .Values.webDeployment.name }}
        image: {{ .Values.webDeployment.dockerImage }}:{{ .Values.webDeployment.dockerTag }}
        ports:
        - containerPort: {{ .Values.webDeployment.port }}
